apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: jupyter-proxy
  namespace: jupyter

spec:
  rules:
    - host: jupyter.kw01
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: proxy-public
                port:
                  number: 80
